version: "3.9"
services:
  openvpn:
    image: kylemanna/openvpn:2.4
    volumes:
      - ovpn-data:/etc/openvpn
      - ovpn-logs:/tmp/
    ports:
      - "1194:1194/udp"
    cap_add:
      - "NET_ADMIN"
  openvpn-viewer:
    image: ghcr.io/martins0n/openvpn-traffic-viewer:0.1.0
    volumes:
      - ovpn-logs:/tmp/
    command:
      - -log "/tmp/openvpn-status.log"

volumes:
  ovpn-data:
    external: true
    name: ovpn-data
  ovpn-logs:
    external: true
    name: ovpn-logs
